apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /volume-dentro-do-container
        name: primeiro-pv
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
          claimName: pvc-2
